version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_DATABASE=session"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
