version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_DATABASE=session"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD=123"
    ports:
      - "3406:3306"
    volumes:
      - ../src/main/resources:/app
